### ISSUE TITLE
README should reference IAnyLink repo

### ISSUE THREAD

**Issue by executed** [benlau/joplin-plugin-ianylink#1]
Just in case you become billionare and forget about IAnyLink web hosting.

Folks need to have a clue what repo serves as a backend here.

Link: https://github.com/benlau/ianylink

P.S. Ben eventually added support of custom IAnyLink service [here](https://github.com/benlau/joplin-plugin-ianylink/releases/tag/release%2F0.1.2)

**Comment by benlau** [comment]
Done
